Support Alternate Registry
EmbarkStudios/cargo-fetcher pull request #131
Opened 2020-09-16 07:19 UTC by m0ssc0de

1. Add a struct `Registry` to store the information of a registry, includes `dl` in it.
2. Find the registries need to be synced from `~/.cargo/config.toml` and `Cargo.lock`. The cargo config should include the `dl` of the registry, like this. 

```toml
[registries]
my-registry = { index = "https://my-intranet:8080/git/index", dl = "http://127.0.0.1/api/v1/crates" }
```
3. The registries that collected at the beginning will be used to mirror and sync itself. The registry stored in krate's source will be used to mirror and sync the crate.
4. Sync the registries and crates parallelly.

2020-09-16 08:53 UTC, Jake-Shadle requested changes
Thanks for the PR! I have other things to do atm, but hopefully can test this locally on our internal repo which uses crates from a private registry sometime this week.

In the meantime, I left a few comments on things that could be cleaned up a bit.

2020-09-16 08:53 UTC, Jake-Shadle commented on src/cmds/main.rs
> +#![type_length_limit = r#"18961884"#]
```suggestion
// Workaround for issue that was exacerbated by rust 1.46.0
#![type_length_limit = r#"18961884"#]
```

2020-09-16 08:53 UTC, Jake-Shadle commented on src/lib.rs
>      CratesIo(String),
I think I'd prefer if these were collapsed into `Registry`, `CratesIo` is just a specific `Registry`.

2020-09-16 08:53 UTC, Jake-Shadle commented on src/lib.rs
> +pub fn read_cargo_config(config_path: &Path) -> Result<HashMap<String, Registry>, Error> {
I'd prefer just a `Vec<>` here, HashMap is a big overkill for what is most likely going to be 1 custom registry.

2020-09-16 08:53 UTC, Jake-Shadle commented on src/lib.rs
>          if source == "registry+https://github.com/rust-lang/crates.io-index" {
Same as previous comment on the `Source` enum, this can be collapsed into a single if block.

2020-09-16 08:53 UTC, Jake-Shadle commented on src/mirror.rs
> +            .instrument(tracing::debug_span!("mirror registry", %index))
```suggestion
            .instrument(tracing::debug_span!("mirror registries", %index))
```

2020-09-16 08:53 UTC, Jake-Shadle commented on src/mirror.rs
> +        ),
We can't rely on the path of the registry to not clash with an actual crate name, it should be safe to just use the short ident for the registry instead.

2020-09-16 11:02 UTC, m0ssc0de commented
> Thanks for the PR! I have other things to do atm, but hopefully can test this locally on our internal repo which uses crates from a private registry sometime this week.
> 
> In the meantime, I left a few comments on things that could be cleaned up a bit.

I appreciate your comments. All improvements and bugs will be processed in 2 days. I hope it could help.

2020-12-09 15:29 UTC, Jake-Shadle commented
Had to refactor a bit in #150, sorry it took so long to get around to this!

2020-12-09 15:29 UTC, closed without merging